application: my-test-app-id
version : 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /.*
  script: app.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

